import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QuestionsProvider from "@/context/QuestionsContext";
import FinalScoreProvider from "@/context/FinalScoreContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 400 500 600 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 400 500 600 900",
});

export const metadata: Metadata = {
  title: "Who wants to be a millionaire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QuestionsProvider>
          <FinalScoreProvider>{children}</FinalScoreProvider>
        </QuestionsProvider>
      </body>
    </html>
  );
}
